name: Deploy Build To Webdock

on:
  push:
    branches:
      - prod
  workflow_dispatch:

env:
  NODE_VERSION: 22

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    concurrency:
      group: webdock-production
      cancel-in-progress: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy build folder to Webdock
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "build/*"
          target: "/var/www/tms-frontend/build"
          overwrite: true

      - name: Reload Nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: sudo systemctl reload nginx
